name = "openai-cf"                # todo
main = "index.js"
compatibility_date = "2022-05-03"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

# replace this with your own
[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "openai-cf"
database_id = "6608f266-33ad-43b0-a017-27683cd6fcb1"

[[vectorize]]
binding = "VECTORIZE_INDEX"   # available within your Worker on env.VECTORIZE_INDEX
index_name = "messages-index"
