name = "openai-cf"                      # todo
main = "index.js"
compatibility_date = "2023-11-21"
compatibility_flags = ["nodejs_compat"]
[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

# replace this with your own
[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "openai-cf"
database_id = "89548016-eedc-47dd-9205-21d94f8cb5c9"

[[vectorize]]
binding = "VECTORIZE_INDEX"   # available within your Worker on env.VECTORIZE_INDEX
index_name = "messages-index"

[[queues.producers]]
queue = "assistant-runs"
binding = "QUEUE"

[[queues.consumers]]
queue = "assistant-runs"
max_batch_size = 1
max_batch_timeout = 30
